spring:
  application:
    name: cms-back-admin
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:cms}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:cms}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 3s
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    include: local

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # 有 XML 时用；纯注解可省略
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发看 SQL；上线关掉
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at # 逻辑删除字段
