brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04 # 删除过期文件
fileReservedTime=48 # 保留时间
brokerRole=ASYNC_MASTER # 异步主节点
flushDiskType=ASYNC_FLUSH # 异步刷盘

brokerIP1=host.docker.internal

autoCreateTopicEnable=true # 自动创建主题
autoCreateSubscriptionGroup=true # 自动创建订阅组

listenPort=10911
mapedFileSizeCommitLog = 268435456 # 日志文件大小 256MB
mapedFileSizeConsumeQueue = 65536 # 消费队列文件大小 64KB