brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
# 同机 jar 通过宿主机端口连 Broker 时用 127.0.0.1
# 远程客户端连公网时改为服务器公网 IP
brokerIP1=127.0.0.1
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
listenPort=10911
mappedFileSizeCommitLog=67108864
mappedFileSizeConsumeQueue=65536
